PolyCare/PolyCare/Models/Medicos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PolyCare.Models {
    public class Medicos {


        public Medicos() {
            Marcacoes = new HashSet<Marcacoes>();
            Atendimentos = new HashSet<Atendimentos>();
            EspecialidadesDoMedico = new HashSet<Especialidades>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // PK não será AutoNumber
        public int MedicoID { get; set; } // PK, por exigência da Entity Framework

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        [Display(Name = "Nome do Médico")]
        [RegularExpression("[A-ZÁÉÍÓÚ][a-záéíóúàèìòùâêîôûãõäëïöüç']+((-| )(((da|de|do|das|dos )))?[A-ZÁÉÍÓÚ][a-záéíóúàèìòùâêîôûãõäëïöüç']+)*", ErrorMessage = "O {0} introduzido não é válido. Os nomes começam por letra maiúscula e não podem ser utilizados números.")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DataNascimento { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        public string Sexo { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        [RegularExpression("[0-9]{9}", ErrorMessage = "Escreva 9 números...")]
        public string NIF { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        [Display(Name = "Data da Entrada na Clínica")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DataEntradaClinica { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        [Display(Name = "Cédula Profissional")]
        //[RegularExpression("[0-9]", ErrorMessage = "Escreva apenas números de 0 a 9...")]
        public string NumCedulaProf { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        [Display(Name = "Data da Inscrição na Ordem")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DataInscOrdem { get; set; }

        [StringLength(50)]
        public string Faculdade { get; set; }

        //##################################################################
        //criar um atributo para ligar este atributo à BD de autenticacao
        //##################################################################
        //[Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        [Display(Name = "Email do Médico")]
        [EmailAddress(ErrorMessage = "O formato deste email não é valido...")]
        public string Username { get; set; }

        //atributo para interligar o médico com o utilizador
        public string ExternalId { get; set; }

        //esta propriedade está excluída da base de dados
        [NotMapped]
        public List<Especialidades> lista { get; set; }

        //#########################################################################
        public virtual ICollection<Especialidades> EspecialidadesDoMedico { get; set; }

        public virtual ICollection<Marcacoes> Marcacoes { get; set; }

        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        //#########################################################################
    }
}

PolyCare/PolyCare/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PolyCare.Models;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace PolyCare.Controllers {
    [Authorize]//força a que só utilizadores AUTENTICADOS consigam aceder aos métodos desta classe (aplica-se a todos os métodos)
    public class MedicosController : Controller {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager {
            get {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set {
                _userManager = value;
            }
        }

        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// index dos médicos
        /// </summary>
        /// <returns></returns>
        // GET: Medicos
        [Authorize(Roles = "Medico,Funcionario,Administrador")]
        public ActionResult Index() {
            if (User.IsInRole("Funcionario") || User.IsInRole("Administrador")) {
                var medicos = db.Medicos.ToList();

                return View(medicos);
            }
            if (User.IsInRole("Medico")) {
                //se chegar aqui, significa que é um médico
                return View(db.Medicos.Where(m => m.Username.Equals(User.Identity.Name)).ToList());
            }
            return View();
        }

        /// <summary>
        /// detalhes de um médico
        /// </summary>
        /// <returns></returns>
        // GET: Medicos/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null) {
                return HttpNotFound();
            }
            return View(medicos);
        }

        //// GET: Medicos/Create
        //public ActionResult Create()
        //{
        //    ViewBag.EspecialidadeFK = new SelectList(db.Especialidades, "EspecialidadeID", "Designacao");
        //    return View();
        //}

        //// POST: Medicos/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "MedicoID,Nome,DataNascimento,Sexo,EspecialidadeFK,NIF,DataEntradaClinica,NumCedulaProf,DataInscOrdem,Faculdade")] Medicos medicos)
        //{
        //    //determinar o ID a atribuir ao novo 'medico'
        //    int novoID = 0;
        //    try {
        //        //perguntar á BD qual o último MedicoID
        //        novoID = db.Medicos.Max(d => d.MedicoID) + 1;
        //    } catch (Exception) {
        //        //não existe dados na BD
        //        //o MAX devolve NULL
        //        novoID = 1;
        //    }
        //    medicos.MedicoID = novoID;
        //    try {
        //        if (ModelState.IsValid) {
        //            //adicionar um novo médico
        //            db.Medicos.Add(medicos);
        //            //guarda as modificacoes
        //            db.SaveChanges();
        //            //redireciona
        //            return RedirectToAction("Index");
        //        }
        //    } catch (Exception ex) {

        //        ModelState.AddModelError("",
        //                            string.Format("Ocorreu um erro na operacão de guardar um novo Medico...")
        //                            );
        //    }


        //    ViewBag.EspecialidadeFK = new SelectList(db.Especialidades, "EspecialidadeID", "Designacao", medicos.EspecialidadeFK);
        //    return View(medicos);
        //}



        //
        // GET: /Account/Register



        //  [AllowAnonymous]

        /// <summary>
        /// método para registar um médico
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Funcionario,Administrador")]
        public ActionResult RegisterMedico() {

            Medicos medico = new Medicos();

            //lista é uma List<Especialidades>
            ViewBag.lista = db.Especialidades.ToList();
            return View(medico);
        }
        
        // POST: /Account/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RegisterMedico(Medicos model, string Password, string ConfirmPassword, string[] Checked) {

            //lista é uma List<Especialidades>
            ViewBag.lista = db.Especialidades.ToList();

            if (Password == "" || ConfirmPassword == "") {
                ModelState.AddModelError("", string.Format("Por favor, preencha os campos de Password e Confirmar Password..."));
                return View(model);
            }
            if (Password != ConfirmPassword || Password.Length < 6) {
                ModelState.AddModelError("", string.Format("Por favor, a Password e a sua confirmação tem que ser iguais, e têm de ter, pelo menos, 6 carateres..."));
                return View(model);
            }

            if (Checked == null) {
                ModelState.AddModelError("", string.Format("Por favor, selecione uma especialidade..."));
                return View(model);
            }

            if (ModelState.IsValid) {
                var user = new ApplicationUser { UserName = model.Username, Email = model.Username };
                var result = await UserManager.CreateAsync(user, Password);

                if (result.Succeeded) {

                    //###################################
                    //tentativa
                    ApplicationDbContext db = new ApplicationDbContext();
                    var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

                    Medicos medico = new Medicos();
                    medico.MedicoID = determinaNovoIdMedico();
                    medico.Nome = model.Nome;
                    medico.DataNascimento = model.DataNascimento;
                    medico.Sexo = model.Sexo;
                    medico.EspecialidadesDoMedico = model.EspecialidadesDoMedico;
                    foreach (var item in Checked) {
                        var idEsp = Convert.ToInt16(item);
                        medico.EspecialidadesDoMedico.Add(db.Especialidades.Select(x=>x).Where(x=>x.EspecialidadeID==idEsp).FirstOrDefault());
                    }
                    //Explicação do Professor
                    ////  medico.EspecialidadeFK = model.EspecialidadeFK;
                    //// * para resolver este problema, 
                    //// *    - na View apresenta-se uma lista de especialidades possiveis (check box list)
                    ////      - na assinatura deste metodo, acrescenta-se o objeto 'check box list'
                    ////          - nao esquecer, validar se houve pelo menos uma especialidade escolhida
                    ////      - criar uma 'lista' de especialidades, com os dados da 'check box list': 
                    ////               var listaDeEspecialidades = new List<Especialidades>();
                    ////      - percorrer a 'check box list' e atribuir valores 'a variavel acima definida
                    ////                foreach +  var especialidade = db.Especialidades.AsNoTracking ().Find(id);
                    ////      - atribuir essa lista ao objeto 'medico'
                    ////              medico.EspecialidadesDoMedico = listaDeEspecialidades;
                    ////   */
                    
                    medico.NIF = model.NIF;
                    medico.DataEntradaClinica = model.DataEntradaClinica;
                    medico.NumCedulaProf = model.NumCedulaProf;
                    medico.DataInscOrdem = model.DataInscOrdem;
                    medico.Faculdade = model.Faculdade;
                    medico.Username = model.Username;
                    medico.ExternalId = user.Id;
                    db.Medicos.Add(medico);
                    var role = userManager.AddToRole(user.Id, "Medico");
                    db.SaveChanges();


                    // await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);

                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        /// <summary>
        /// determina o id do novo médico
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Funcionario,Administrador")]
        private int determinaNovoIdMedico() {

            ApplicationDbContext db = new ApplicationDbContext();
            //determinar o ID a atribuir ao novo 'médico'
            int novoID = 0;
            try {
                //perguntar á BD qual o último DonoID
                novoID = db.Medicos.Max(p => p.MedicoID) + 1;

PolyCare/PolyCare/Views/Medicos/Create.cshtml
@model PolyCare.Models.Medicos

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EspecialidadeFK, "EspecialidadeFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EspecialidadeFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EspecialidadeFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NIF, htmlAttributes: new { @class = "control-label col-md-2", @maxlength="9" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NIF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NIF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataEntradaClinica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataEntradaClinica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataEntradaClinica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumCedulaProf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumCedulaProf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumCedulaProf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataInscOrdem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataInscOrdem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataInscOrdem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Faculdade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Faculdade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Faculdade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PolyCare/PolyCare/Views/Medicos/Delete.cshtml
@model PolyCare.Models.Medicos

@{
    ViewBag.Title = "Delete";
}

<h2>Apagar</h2>

<h3>Tem a certeza que pretende apagar este médico?</h3>
@if (TempData["notice"] != null) {
    <p class="alert-danger">@TempData["notice"]</p>
}
<div>
    <h4>Médico</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Especialidade.Designacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidade.Designacao)
        </dd>*@


        <dt>
            <span class="glyphicon glyphicon-user"></span>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-piggy-bank"></span>
            @Html.DisplayNameFor(model => model.NIF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NIF)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.DisplayNameFor(model => model.DataEntradaClinica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataEntradaClinica)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-pencil"></span>
            @Html.DisplayNameFor(model => model.NumCedulaProf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumCedulaProf)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.DisplayNameFor(model => model.DataInscOrdem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataInscOrdem)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-pencil"></span>
            @Html.DisplayNameFor(model => model.Faculdade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Faculdade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

PolyCare/PolyCare/Views/Medicos/Details.cshtml
@model PolyCare.Models.Medicos

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Médicos</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Especialidade.Designacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidade.Designacao)
        </dd>*@

        <dt>
            <span class="glyphicon glyphicon-user"></span>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-piggy-bank"></span>
            @Html.DisplayNameFor(model => model.NIF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NIF)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.DisplayNameFor(model => model.DataEntradaClinica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataEntradaClinica)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-pencil"></span>
            @Html.DisplayNameFor(model => model.NumCedulaProf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumCedulaProf)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.DisplayNameFor(model => model.DataInscOrdem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataInscOrdem)
        </dd>

        <dt>
            <span class="glyphicon glyphicon-pencil"></span>
            @Html.DisplayNameFor(model => model.Faculdade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Faculdade)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.MedicoID }) |
    @Html.ActionLink("Voltar", "Index")
</p>

PolyCare/PolyCare/Views/Medicos/Index.cshtml
@model IEnumerable<PolyCare.Models.Medicos>

@{
    ViewBag.Title = "Index";
}

<h2>Médicos</h2>

<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.Especialidade.Designacao)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NIF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataEntradaClinica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumCedulaProf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataInscOrdem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Faculdade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.Especialidade.Designacao)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataNascimento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NIF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataEntradaClinica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumCedulaProf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataInscOrdem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Faculdade)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.MedicoID }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.MedicoID }) |
            @Html.ActionLink("Apagar", "Delete", new { id=item.MedicoID })
        </td>
    </tr>
}

</table>

PolyCare/PolyCare/Views/Medicos/RegisterMedico.cshtml
@model PolyCare.Models.Medicos
@using PolyCare.Models
@{
    ViewBag.Title = "Registar Médico";
    IEnumerable<Especialidades> esp = ViewBag.lista;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("RegisterMedico", "Medicos", FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
    @Html.AntiForgeryToken()
    <h4>Criar uma nova conta de médico</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.Nome, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-user"></span>
            @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", @placeholder = "Nome" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DataNascimento, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.EditorFor(m => m.DataNascimento)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Sexo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-heart"></span>
            @Html.RadioButtonFor(m => m.Sexo, "Masculino") Masculino
            @Html.RadioButtonFor(m => m.Sexo, "Feminino") Feminino
        </div>
    </div>
   
    <div class="form-group">
        @Html.LabelFor(m => m.NIF, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-piggy-bank"></span>
            @Html.TextBoxFor(m => m.NIF, new { @class = "form-control", @maxlength = "9", @placeholder = "NIF" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.DataEntradaClinica, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.EditorFor(m => m.DataEntradaClinica)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NumCedulaProf, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-pencil"></span>
            @Html.TextBoxFor(m => m.NumCedulaProf, new { @class = "form-control", @maxlength = "9", @placeholder = "Número da Cédula Profissional" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DataInscOrdem, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.EditorFor(m => m.DataInscOrdem)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Faculdade, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-pencil"></span>
            @Html.TextBoxFor(m => m.Faculdade, new { @class = "form-control", @placeholder = "Faculdade" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Especialidade", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <span class="glyphicon glyphicon-star"></span>
           @foreach(var item in esp) {
               <p></p>
               <input type="checkbox" id="@item.EspecialidadeID" name="Checked" value="@item.EspecialidadeID" />@item.Designacao              
           }

        </div>
     </div>

        //#######################
        <div class="form-group">
            @Html.LabelFor(m => m.Username, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <span class="glyphicon glyphicon-envelope"></span>
                @Html.TextBoxFor(m => m.Username, new { @class = "form-control", @placeholder = "Endereço de Email" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Password", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <span class="glyphicon glyphicon-lock"></span>
                @Html.Password("Password", null, new { @class = "form-control", @placeholder = "Password" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("ConfirmPassword", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <span class="glyphicon glyphicon-lock"></span>
                @Html.Password("ConfirmPassword", null, new { @class = "form-control", @placeholder = "Password novamente" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Registar" />
            </div>
        </div>


        }

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }