PolyCare/PolyCare/Models/Carrousel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PolyCare.Models {
    public class Carrousel {
        //id da imagem
        public int ID { get; set; }

        //id do Funcionário que insere a imagem
        public string IdFuncionario { get; set; }


        //data e hora da inserção da imagem
        [Display(Name = "Data|Hora de Inserção")]
        public DateTime TimeStamp { get; set; }

        //título da imagem
        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório.")]
        [Display(Name = "Título")]
        [RegularExpression("[A-ZÁÉÍÓÚ][a-záéíóúàèìòùâêîôûãõäëïöüç']+((-| )(((da|de|do|das|dos )))?[A-ZÁÉÍÓÚ][a-záéíóúàèìòùâêîôûãõäëïöüç']+)*", ErrorMessage = "O {0} introduzido não é válido.")]
        public string Title { get; set; }

        //endereço da imagem
        [Display(Name = "Nome da Imagem")]
        public string ImgSource { get; set; }
    }
}

PolyCare/PolyCare/Controllers/CarrouselsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PolyCare.Models;
using Microsoft.AspNet.Identity;

namespace PolyCare.Controllers {
    [Authorize(Roles = "Funcionario")]
    public class CarrouselsController : Controller {
        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// retorna a extensão de um ficheiro
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        public string GetExtensao(string fileName) {
            fileName = fileName.Substring(fileName.LastIndexOf("/") + 1);
            return "." + fileName;
        }

        /// <summary>
        /// index das imagens
        /// </summary>
        /// <returns></returns>
        // GET: Carrousels
        public ActionResult Index() {
            return View(db.Carrousels.ToList());
        }

        /// <summary>
        /// adicionar uma nova imagem ao Carrousel
        /// </summary>
        /// <returns></returns>
        // GET: Carrousels/Create
        public ActionResult AddImage() {
            return View();
        }

        // POST: Carrousels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddImage([Bind(Include = "ID,IdFuncionario,TimeStamp,Title,ImgSource")] Carrousel carrousel, HttpPostedFileBase file) {
            //array com os diferentes tipos possíveis de extensões
            string[] extensions = new string[] { "jpeg", "jpg", "bmp", "png" };


            //atribui o id à nova imagem (calculado através da lista das existentes + 1)
            int ImageId = db.Carrousels.ToList().Count + 1;

            //atribui o carrousel ID com o ImageId anteriormente calculado
            carrousel.ID = ImageId;

            //atribui a data e hora da inserção da imagem
            carrousel.TimeStamp = DateTime.Now;

            //atribui o IdFuncionario da imagem ao id do utilizador autenticado
            carrousel.IdFuncionario = User.Identity.GetUserId();

            if (ModelState.IsValid) {

                //se o ficheiro introduzido não for nulo
                if (file != null) {
                    //verifica se o tipo de ficheiro coincide com os tipos de ficheiros possíveis
                    if (extensions.Contains(file.ContentType.Substring(file.ContentType.LastIndexOf("/") + 1))) {

                        //endereço da imagem
                        string endereco = ImageId + GetExtensao(file.ContentType);

                        //caminho da imagem
                        string path = Server.MapPath("~/Content/Images/Carrousel") + "\\" + endereco;
                        file.SaveAs(path);

                        //atribui o endereço
                        carrousel.ImgSource = endereco;

                        //adiciona
                        try {
                            db.Carrousels.Add(carrousel);
                            db.SaveChanges();
                        } catch (Exception) {

                            //se chegar aqui, significa que não se conseguiu guardar na base de dados
                            TempData["notice"] = "Ocorreu um erro ao guardar na base de dados.";
                            return View(carrousel);
                        }
                        return RedirectToAction("Index");
                    }

                    //se chegar aqui, significa que o tipo de ficheiro introduzido não é válido
                    TempData["notice"] = "Por favor, selecione uma imagem válida [precisa ser do tipo jpeg, jpg, bmp ou png].";

                    return View(carrousel);
                }
                //se chegar aqui, significa que a imagem não foi carregada
                return View(carrousel);
            }


            return View(carrousel);
        }

        /// <summary>
        /// edita uma imagem do carrousel
        /// </summary>
        /// <returns></returns>
        // GET: Carrousels/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carrousel carrousel = db.Carrousels.Find(id);
            if (carrousel == null) {
                return HttpNotFound();
            }
            return View(carrousel);
        }

        // POST: Carrousels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IdFuncionario,TimeStamp,Title,ImgSource")] Carrousel carrousel) {
            if (ModelState.IsValid) {
                db.Entry(carrousel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carrousel);
        }

        /// <summary>
        /// apaga uma imagem do Carrousel
        /// </summary>
        /// <returns></returns>
        // GET: Carrousels/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carrousel carrousel = db.Carrousels.Find(id);
            if (carrousel == null) {
                return HttpNotFound();
            }
            return View(carrousel);
        }

        // POST: Carrousels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Carrousel carrousel = db.Carrousels.Find(id);
            db.Carrousels.Remove(carrousel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PolyCare/PolyCare/Views/Carrousels/AddImage.cshtml
@model PolyCare.Models.Carrousel

@{
    ViewBag.Title = "Create";
}

<h2>Submeter Imagem</h2>
@if (TempData["notice"] != null) {
    <p class="alert-danger">@TempData["notice"]</p>
}

@using (Html.BeginForm("AddImage", "Carrousels", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="glyphicon glyphicon-pencil"></span>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Título" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="file" class="control-label col-md-4">Escolher imagem</label>
            <div class="col-md-6">
                <span class="glyphicon glyphicon-picture"></span>
                <input type="file" name="file" style="width: 50%;" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submeter" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para as Imagens", "Index")
</div>

PolyCare/PolyCare/Views/Carrousels/Delete.cshtml
@model PolyCare.Models.Carrousel

@{
    ViewBag.Title = "Delete";
}

<h2>Apagar</h2>

<h3>Tem a certeza que pretende apagar esta imagem?</h3>
<div>
    <h4>Carrousel</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgSource)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgSource)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

PolyCare/PolyCare/Views/Carrousels/Edit.cshtml
@model PolyCare.Models.Carrousel

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Carrousel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

PolyCare/PolyCare/Views/Carrousels/Index.cshtml
@model IEnumerable<PolyCare.Models.Carrousel>

@{
    ViewBag.Title = "Index";
}

<h2>Imagens na Página Inicial</h2>

@if (Model.Count() == 0) {
    <p>Sem imagens.</p>
}
    
@foreach (var item in Model) {
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-11" style="text-align:center;">
                    <h4>@item.Title</h4>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-9">
                                    <img src="~/Content/Images/Carrousel/@(item.ImgSource)"  width="700" height="350"/>
                                </div>
                                <div class="col-md-3">
                                    <div class="row">
                                        Inserido: @item.TimeStamp
                                    </div>
                                    <div class="row">
                                        @Html.ActionLink("Editar", "Edit", new { id = item.ID }, new { @class = "label label-warning" })
                                    </div>
                                    <div class="row">
                                        @Html.ActionLink("Eliminar", "Delete", new { id = item.ID }, new { @class = "label label-danger" })                                  
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
  